### PR TITLE
this is a github actions test

### PR DESCRIPTION
**Pull request by ItsIgnacioPortal**

### CODE REVIEW

**Comment by ItsIgnacioPortal** [comment]
Hey @righettod, can you aprove the workflow run?

**Comment by righettod** [comment]
Done ✅

**Comment by ItsIgnacioPortal** [comment]
The github action doesn't seem to be working correctly. The content I added did not start with a slash, but the github action failed anyway. @righettod do you know why this happened?

**Comment by righettod** [comment]
@ItsIgnacioPortal Thanks a lot for the notification. Something changed since the initial PR that made the workflow to be broken...

I changed the approach to fix the issue and made the check more easy to maintain/evolve

image

image

I will update the desrc of the PR with now approach.

**Comment by righettod** [comment]
PR https://github.com/danielmiessler/SecLists/pull/800 updated with changes.

**Pull request closed without merging**
